name: "hw_edl_week_02"
device: "cuda"
optimizer: "adam"
eps_adam: 1e-08
lr: 1e-5
batch_size: 128
num_workers: 4
has_flip: False
flip_prob: 0.05
unet_params: [3, 3, 128]
diffusion_params: [1e-4, 0.02]
num_timesteps: 1000
num_epochs: 100
cfg_name: "default"
api_key: f584b3b7e8a09e6e6af3c36642280e28f629a518
test_cpu: False